

rule target:
    input:
        panel="results/plots/survival_mod_panel.svg",
        epi="results/plots/epi_test/epi.svg",
        obs="results/plots/epi_test/obs.svg",
        mean_diffs="results/plots/epi_test/mean_diffs.svg",
        traits="results/posteriors/traits.csv",
        betas="results/posteriors/betas.csv",
        diffs="results/posteriors/diffs.csv",
        corrs="results/posteriors/corrs.csv",
        ppc="results/plots/post_pred/ppc.svg"

# this rule takes the files from data collectio and creates the set 
# of files that will be used for the analysis

rule data_wrangling:
    input:
        day_4="resources/day_4_areas.csv",
        day_17="resources/day_17_areas.csv",
        ids="resources/germ_and_id.csv",
        height="resources/heights.csv",
        drought="resources/seed_growth_vs_seed_size.csv"
    output:
        traits="results/wrangled/traits.csv",
        long="results/wrangled/drought_long.csv",
        short="results/wrangled/drought_short.csv"
    log:
        log="results/logs/data_wrangling.log"
    conda:
        "envs/wrangling.yaml"
    script:
        "scripts/data_wrangling.R"


# this rule doesn't really do anything, it just spits out a file that says "stan files updated", the purpose of the
# rule is to get the stan files as input in the workflow so that when they are modified it triggers the workflow
# to re-create anything that is dependent on the stan files.
rule stan_compile:
    input:
        rgr="workflow/scripts/stan/drought_survival_rgr.stan",
        sze="workflow/scripts/stan/drought_survival_size.stan",
        rgr_size="workflow/scripts/stan/drought_survival_rgr_size.stan"
    output:
        "workflow/scripts/stan/compile_complete.txt"
    log:
        log="results/logs/compile.log"
    conda:
        "envs/cmdstanr.yaml"
    shell:
        """
        (echo stan files updated > {output}) 2> {log}
        """




# run the stan code to fit the growth rate/survival model

rule drought_survival:
    input:
        long="results/wrangled/drought_long.csv",
        short="results/wrangled/drought_short.csv",
        traits="results/wrangled/traits.csv",
        compiled="workflow/scripts/stan/compile_complete.txt"
    output:
        rgr="results/drought_survival_rgr.RDS",
        sze="results/drought_survival_size.RDS",
        rgr_size="results/drought_survival_rgr_size.RDS"
    params:
        rgr="workflow/scripts/stan/drought_survival_rgr.stan",
        sze="workflow/scripts/stan/drought_survival_size.stan",
        rgr_size="workflow/scripts/stan/drought_survival_rgr_size.stan"
    log:
        log="results/logs/drought_survival_model.log"
    conda:
        "envs/cmdstanr.yaml"
    threads:
        4
    script:
        "scripts/drought_survival.R"

rule post_pred_checks:
    input:
        fit="results/drought_survival_rgr.RDS",
        short="results/wrangled/drought_short.csv"
    output:
        "results/plots/post_pred/ppc.svg"
    log:
        log="results/logs/post_pred_checks.log"
    conda:
        "envs/plots.yaml"
    script:
        "scripts/ppc_plots.R"

rule survival_plots:
    input:
        size_mod="results/drought_survival_size.RDS",
        rgr_mod="results/drought_survival_rgr.RDS",
        rgr_size_mod="results/drought_survival_rgr_size.RDS",
        short="results/wrangled/drought_short.csv",
        long="results/wrangled/drought_long.csv"
    output:
        panel="results/plots/survival_mod_panel.svg"
    log:
        log="results/logs/survival_plots.log"
    conda:
        "envs/plots.yaml"
    script:
        "scripts/survival_plots.R"

rule trait_boots:
    input:
        traits="results/wrangled/traits.csv"
    output:
        survive="results/trait_boots/survive.csv",
        day_4="results/trait_boots/day_4.csv",
        day_17="results/trait_boots/day_17.csv",
        rgr="results/trait_boots/rgr.csv",
        height="results/trait_boots/height.csv"
    log:
        log="results/logs/trait_boots.log"
    conda:
        "envs/wrangling.yaml"
    script:
        "scripts/trait_boots.R"

rule epi_plots:
    input:
        survive="results/trait_boots/survive.csv",
        day_4="results/trait_boots/day_4.csv",
        day_17="results/trait_boots/day_17.csv",
        rgr="results/trait_boots/rgr.csv",
        height="results/trait_boots/height.csv",
        traits="results/wrangled/traits.csv"
    output:
        epi="results/plots/epi_test/epi.svg",
        obs="results/plots/epi_test/obs.svg",
        mean_diffs="results/plots/epi_test/mean_diffs.svg"
    log:
        log="results/logs/epi_plots.log"
    conda:
        "envs/plots.yaml"
    script:
        "scripts/epi_plots.R"

rule get_posterior:
    input:
        survive="results/trait_boots/survive.csv",
        day_4="results/trait_boots/day_4.csv",
        day_17="results/trait_boots/day_17.csv",
        rgr="results/trait_boots/rgr.csv",
        height="results/trait_boots/height.csv",
        mod_size="results/drought_survival_size.RDS",
        mod_rgr="results/drought_survival_rgr.RDS",
        mod_rgr_size="results/drought_survival_rgr_size.RDS",
        short="results/wrangled/drought_short.csv",
        long="results/wrangled/drought_long.csv"
    output:
        traits="results/posteriors/traits.csv",
        betas="results/posteriors/betas.csv",
        diffs="results/posteriors/diffs.csv",
        corrs="results/posteriors/corrs.csv"
    log:
        log="results/logs/get_posteriors.log"
    conda:
        "envs/plots.yaml"
    script:
        "scripts/get_posteriors.R"
